/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    AButton: typeof import('ant-design-vue/es')['Button']
    ACard: typeof import('ant-design-vue/es')['Card']
    ACardMeta: typeof import('ant-design-vue/es')['CardMeta']
    AInput: typeof import('ant-design-vue/es')['Input']
    AInputSearch: typeof import('ant-design-vue/es')['InputSearch']
    ALayoutHeader: typeof import('ant-design-vue/es')['LayoutHeader']
    AModal: typeof import('ant-design-vue/es')['Modal']
    ATypographyTitle: typeof import('ant-design-vue/es')['TypographyTitle']
    AuthModal: typeof import('./src/components/AuthModal.vue')['default']
    Card: typeof import('./src/components/Card.vue')['default']
    Container: typeof import('./src/components/Container.vue')['default']
    ImageGallery: typeof import('./src/components/ImageGallery.vue')['default']
    Modal: typeof import('./src/components/Modal.vue')['default']
    Nav: typeof import('./src/components/Nav.vue')['default']
    Profile: typeof import('./src/components/Profile.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Timeline: typeof import('./src/components/Timeline.vue')['default']
    Userbar: typeof import('./src/components/Userbar.vue')['default']
    UserBar: typeof import('./src/components/UserBar.vue')['default']
  }
}
